# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils.ipynb.

# %% auto #0
__all__ = ['find_project_root']

# %% ../../nbs/utils.ipynb #b9c83adf
import os
from fastcore.all import Path, L

# %% ../../nbs/utils.ipynb #999a627d
def find_project_root():
    path = Path(os.path.abspath('__file__'))
    while True:
        root_files = L('setup.py', 'settings.ini', 'pyproject.toml')
        # if (
        #     (path / "setup.py").exists()
        #     and (path / "settings.ini").exists()
        #     and (path / "pyproject.toml").exists()
        # ):
        #     return path
        if all((path / f).exists() for f in root_files): return path
    

        # 一つ上のディレクトリへ移動
        path = path.parent
        if path == Path("/"):
            raise ValueError("Project root not found.")
