# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils.ipynb.

# %% auto #0
__all__ = ['find_project_root']

# %% ../../nbs/utils.ipynb #52dfbcc2
import os
from fastcore.all import Path, L

# %% ../../nbs/utils.ipynb #0c38da64
def find_project_root():
    path = Path(os.path.abspath('__file__'))
    while True:
        root_files = L('flake.nix', '.gitignore', 'pyproject.toml')
        if all((path / f).exists() for f in root_files): return path
        path = path.parent
        if path == Path("/"): raise ValueError("Project root not found.")
