[DEFAULT]
# All sections below are required unless otherwise specified
# see https://github.com/fastai/nbdev/blob/master/settings.ini for examples

### Python Library ###
lib_name = uv2nix_nbdev_template
min_python = 3.12
version = 0.1.0

### OPTIONAL ###

# requirements = fastcore
# dev_requirements =
# console_scripts =

### nbdev ###
nbs_path = nbs
doc_path = docs
recursive = True
tst_flags = notest

### Documentation ###
host = github
repo = uv2nix-nbdev-template
branch = main
custom_sidebar = True

### PyPI ### 
audience = Developers
author = KaoruBB
author_email = {kaorubabasaki@gmail.com}
# copyright = Put your copyright info here
description = A minimal template for nbdev projects using uv2nix 
keywords = template uv2nix nbdev
language = English
license = Proprietary
status = 2
user = KaoruBB

### Inferred From Other Values ###
doc_host =  https://%(user)s.github.io
doc_baseurl = /%(lib_name)s/
git_url = https://github.com/%(user)s/%(repo)s/
lib_path = src/%(lib_name)s
title = %(lib_name)s
