# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/uv2nix_nbdev_template',
                'doc_host': 'https://KaoruBB.github.io',
                'git_url': 'https://github.com/KaoruBB/uv2nix-nbdev-template',
                'lib_path': 'src/uv2nix_nbdev_template'},
  'syms': { 'uv2nix_nbdev_template.utils': { 'uv2nix_nbdev_template.utils.find_project_root': ( 'utils.html#find_project_root',
                                                                                                'uv2nix_nbdev_template/utils.py')}}}
