# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils.ipynb.

# %% auto #0
__all__ = ['find_project_root']

# %% ../../nbs/utils.ipynb #d2439d37
from fastcore.all import Path, L

# %% ../../nbs/utils.ipynb #692d6a30
def find_project_root():
    try: path = Path(__file__).resolve().parent
    except NameError: path = Path.cwd().resolve()
    while True:
        root_files = L('flake.nix', '.gitignore', 'pyproject.toml')
        if all((path / f).exists() for f in root_files): return path
        path = path.parent
        if path == Path("/"): raise ValueError("Project root not found.")
